# Generated by Django 5.0.2 on 2026-02-26 10:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nom de l'actif"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BOUCHE", "Bouche incendie"),
                            ("ARMOIRE", "Armoire technique"),
                            ("PANNEAU", "Panneau"),
                            ("REGARD", "Regard"),
                            ("AUTRE", "Autre équipement"),
                        ],
                        default="AUTRE",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OP", "Opérationnel"),
                            ("CH", "À vérifier"),
                            ("OS", "Hors service"),
                        ],
                        default="OP",
                        max_length=2,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
